on:
  pull_request: null
  push:
    branches:
      - master

name: phpunit

permissions:
  contents: read

jobs:
  phpunit:
    uses: spiral/gh-actions/.github/workflows/phpunit.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      stability: >-
        ['prefer-stable']
